# Generated by Django 5.0 on 2023-12-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.IntegerField(),
        ),
    ]
